config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :turns
  end

  resources :turns do
    resources :guesses
  end

  resources :guesses do
  end

  root 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :turns

  def next_player_up
    turns_count = turns.count
    players.all[turns_count % players.count]
  end
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :player
  belongs_to :turn
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
end

app/models/turn.rb
class Turn < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  has_many :guesses

  def image_url
    image
  end

  def all_images
    [
      "http://i.imgur.com/OvcVXWs.png",
      "http://i.imgur.com/f3fGIdN.jpg",
      "http://i.imgur.com/aqypouN.gif",
      "http://images.mtvnn.com/6fbf76d7619ed69fecab2d3a85ef3dad/630x354_",
      "http://i.imgur.com/5yAaA.gif",
      "http://i3.kym-cdn.com/photos/images/newsfeed/000/639/371/38d.gif",
      "http://i.imgur.com/OMYZDXZ.gif",
      "http://i.imgur.com/jxY7Ywz.gif",
      "http://i.imgur.com/6SwrGlJ.gif",
      "http://i.imgur.com/TnmlzlU.gif",
      "http://i.imgur.com/JBJn8Ub.gif",
      "http://i.imgur.com/mGMbe8Z.gif",
      "http://giant.gfycat.com/SleepyThisGreendarnerdragonfly.gif",
      "http://i.imgur.com/SYoHIJs.gif",
      "http://i.imgur.com/wokJbxx.gif",
      "http://i.imgur.com/My1Dqvg.gif",
      "http://i.imgur.com/Xsu770n.jpg",
      "http://i.imgur.com/DjCHGiU.gif",
      "http://i.imgur.com/feJySi4.gif",
      "http://i.imgur.com/yyZwINK.jpg",
      "http://i.imgur.com/47Ef2vQ.jpg",
      "http://buylaughs.com/wp-content/uploads/2014/01/Funny-Babies-Pictures-2.jpg",
      "http://www.hdquotesvsmemes.com/wp-content/uploads/2014/08/funny-photo-pics-2-500x487.jpg",
    ]
  end

  def guessing_players
    game.players.where.not(id: player.id)
  end

  def guessed?
    guesses.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]


  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new
    player_names = params.require(:game).permit(:player_names).fetch(:player_names).split(',')
    player_names.map { |n| @game.players.build(name: n.strip) }

    respond_to do |format|
      if @game.save
        format.html { redirect_to new_game_turn_path(@game), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game)
    end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_turn, only: [:index, :create]
  # GET /guesses
  # GET /guesses.json
  def index
  end

  def create
    @turn.guessing_players.each do |player|

      if params[:player] && params[:player][player.id.to_s]
        Guess.create!(turn: @turn, player_id: player.id, lie: true)
      else
        Guess.create!(turn: @turn, player_id: player.id, lie: false)
      end
    end

    redirect_to turn_path(@turn)
  end

  private

  def set_turn
    @turn = Turn.find(params[:turn_id])
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_game, only: [:new]
  before_action :set_turn, only: [:show, :update]

  # GET /games/new
  def new
    @turn = @game.turns.new
    @turn.player = @game.next_player_up
    @turn.image = @turn.all_images.sample
  end

  # GET /turns/1
  # GET /turns/1.json
  def show
  end

  # POST /turns
  # POST /turns.json
  def create
    @turn = Turn.new(turn_params)

    respond_to do |format|
      if @turn.save
        format.html { redirect_to @turn }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1
  # PATCH/PUT /turns/1.json
  def update
    respond_to do |format|
      # Booleans need to be set manually
      if !turn_params['lie']
        modified_turn_params = turn_params.merge(lie: false)
      else
        modified_turn_params = turn_params
      end

      if @turn.update(modified_turn_params)
        format.html { redirect_to turn_guesses_path(@turn), notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @turn }
      else
        format.html { render :edit }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_turn
    @turn = Turn.find(params[:id])
  end

  def turn_params
    params.required(:turn).permit(:game_id, :player_id, :image, :lie)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.haml
.row
  .columns.medium-4.medium-offset-4.text-center
    %h1.text-center Enter Players

    %form.add-players
      %textarea

    %button.add-player-button.button Add Players

    =form_for :game, url: games_path, html: {class: 'start-game'} do
      %input{type: 'hidden', name:'game[player_names]', value: '[]'}
      %button.start.button Start

    %p
      %span.player-count 0
      %span Players
    %ul.no-bullet.players

:coffeescript
  $ ->
    # Add player
    $('.add-player-button').click (e) ->
      e.preventDefault()
      $textArea = $('form.add-players textarea')
      $('.players').append(
        '<li class="player">'  + $textArea.val() + '</li>'
      )
      $textArea.val('')
      $('.player-count').html($('.player').length)

    # Start game
    $('form.start-game').click (e) ->
      e.preventDefault()
      $form = $('form.start-game')
      players = _($(".player")).map (p) -> p.innerText
      $form.find("input[name='game[player_names]']").val(players)
      $form.submit()

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/guesses/index.html.haml
.row
  .columns.medium-4.medium-offset-4.text-center
    %p= "Is #{@turn.player.name} telling the truth or lying?"

    %p= "Submit your guesses"

    = form_tag turn_guesses_path(@turn) do |f|
      - @turn.guessing_players.each do |player|
        %p= player.name
        .switch
          %input.switch-input{type: "checkbox", name:"player[#{player.id}][lie]", id: "lies-#{player.id}"}
          %label.switch-paddle{for: "lies-#{player.id}", style: 'display: 100px; '}
            %span.show-for-sr Do you like me?
            %span.switch-active Truth
            %span.switch-inactive Lies!

      %input.button{type: 'submit', value: 'Submit'}


:coffeescript
  $ ->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Wiompi" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/turns/new.html.haml
.row
  .columns.medium-4.medium-offset-4.text-center
    %h1.text-center= "Hey #{@turn.player.name}"

    %p It's your turn

    =form_for @turn do
      =hidden_field(:turn, :image)
      =hidden_field(:turn, :game_id)
      =hidden_field(:turn, :player_id)

      %input.button.submit{type: 'submit', value: "Ready"}

app/views/turns/show.html.haml
.row
  .columns.medium-4.medium-offset-4.text-center
    %br
    %br
    -if @turn.guessed?
      %p= "#{@turn.player.name}'s image:"

      %img{src: @turn.image_url}

      %h3
        -if @turn.lie
          It was a lie
        -else
          It was the truth!

      %a.button{href: new_game_turn_path(@turn.game)} Next

    -else
      %p= "#{@turn.player.name}, you are the Teller. Describe your image"

      %img.img-url{src: @turn.image_url}


      =form_for @turn do |form|
        %input.hide{type: 'checkbox', name: 'turn[lie]'}
        =form.hidden_field(:image)

        %input.switch-input{type: "checkbox", name:"turn[lie]", id: "lie_input"}
        %label.switch-paddle{for: "lie_input"}
          %span.show-for-sr Do you like me?
          %span.switch-active I'll lie
          %span.switch-inactive I won't lie

        %br
        %input.turn-submit-button.button{type: 'submit', value: "Enter Guesses"}

:coffeescript
  $ ->
    # Add player
    $('.lie-button').click (e) ->
      e.preventDefault()
      $("input[name='turn[lie]']").prop('checked', true)

    $('.truth-button').click (e) ->
      e.preventDefault()
      $("input[name='turn[lie]']").prop('checked', false)

app/views/welcome/index.html.haml
.row
  .columns.col-sm-12.text-center
    %h1.text-center Wiompi
    %p.text-center what is on my phone is...

    %p A Game of

    %span Truth
    %span and
    %span Lies

    %br
    %br

    %a.button{href: new_game_path} Start